---
- hosts: app
  become: true
  become_user: root
  roles:
    - nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        reverse_proxy:
          locations:
            frontend:
              location: /
              proxy_pass: http://52.174.0.165
            backend:
              location: /backend
              proxy_pass: http://localhost:5000
        upstreams:
          upstream_1:
            name: frontend_servers
            lb_method: least_conn
            zone_name: frontend
            zone_size: 64k
            sticky_cookie: false
            servers:
              frontend_server_1:
                address: 52.174.0.165
                port: 80
                weight: 1
                health_check: max_fails=3 fail_timeout=5s
          upstream_2:
            name: backend_servers
            lb_method: least_conn
            zone_name: backend
            zone_size: 64k
            sticky_cookie: false
            servers:
              backend_server_1:
                address: localhost
                port: 5000
                weight: 1
                health_check: max_fails=3 fail_timeout=5s