---

- name: Install putty
  hosts: stepping
  connection: winrm
  gather_facts: false

  tasks:
   - name: Download Putty
     win_get_url:
      url: 'https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.70-installer.msi'
      dest: 'C:\Users\Public\Downloads'
   
   - name: Install Putty
     win_package:
      path: 'C:\Users\Public\Downloads\putty-64bit-0.70-installer.msi'
      state: present
