---

- name: start initializing
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - loadbalancer_vars.yml
  
  tasks:

  - name: create load balancer pip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group_name }}"
      name: "{{ public_ip_name }}"
      allocation_method: Dynamic

  - name: create load balancer
    become: yes
    become_user: root
    azure_rm_loadbalancer:
      resource_group: "{{ resource_group_name }}"
      name: "{{ loadbalancer_name }}"
      frontend_ip_configurations:
        - name: frontendipconf0
          public_ip_address: "{{ public_ip_name }}"
      backend_address_pools:
        - name: "{{ backend_pool_name }}"
      probes:
        - name: prob0
          port: 80
      load_balancing_rules:
        - name: "{{ loadbalancingrule_name }}"
          frontend_ip_configuration: frontendipconf0
          backend_address_pool: "{{ backend_pool_name }}"
          frontend_port: 5000
          backend_port: 5000
          probe: prob0

  - name: Add interface to loadbalancer backend address pool
    become: yes
    become_user: root
        
    azure_rm_networkinterface:
      name: "{{ network_card_name }}"
      resource_group: "{{ resource_group_name }}"
      subnet_name: "{{ frontend_subnet }}"
      virtual_network: "{{ virtual_network_name }}"
      security_group: "{{ security_group_frontend }}"
      ip_configurations:
        - name: frontendip
          load_balancer_backend_address_pools:
          - name: "{{ backend_pool_name }}"
            load_balancer: "{{ loadbalancer_name }}"
