---

- name: test load
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:

  - name: create load balancer
    become: yes
    become_user: root
    azure_rm_loadbalancer:
      resource_group: zuyrg00007
      name: loadbalancer001
      frontend_ip_configurations:
        - name: frontendipconf0
          public_ip_address: LoadBalancer
      backend_address_pools:
        - name: backendaddrpool0
      probes:
        - name: prob0
          port: 80
      load_balancing_rules:
        - name: lbrbalancingrule0
          frontend_ip_configuration: frontendipconf0
          backend_address_pool: backendaddrpool0
          frontend_port: 80
          backend_port: 80
          probe: prob0

  - name: Add interface to loadbalancer backend address pool
    become: yes
    become_user: root
        
    azure_rm_networkinterface:
      name: loadbalancer
      resource_group: zuyrg00007
      subnet_name: Frontend_subnet
      virtual_network: Vnet_Wandel_App
      security_group: App-server-nsg
      ip_configurations:
        - name: frontendip
          load_balancer_backend_address_pools:
          - name: backendaddrpool0
            load_balancer: loadbalancer001
