---

- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - appserver_vars.yml
    - vault.yml
  no_log: true

  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group_name }}"
      allocation_method: Dynamic
      name: "{{ public_ip_address_name }}"
    register: output_ip_address

  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group_name }}"
      name: "{{ network_card_name }}"
      virtual_network: "{{ virtual_network_name }}"
      subnet: "{{ subnet_name }}"
      public_ip_name: "{{ public_ip_address_name }}"
      security_group: Frontend-nsg
      ip_configurations:
        - name: Appserver
          load_balancer_backend_address_pools:
          - name: backendaddrpool0
            load_balancer: loadbalancer1
      register: NIC_log

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vm_name }}"
      location: westeurope
      vm_size: Standard_B1s
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password_appserver }}"
      managed_disk_type: Premium_LRS
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/Admingroep7/.ssh/authorized_keys
          key_data: "{{ ssh_key_app }}"
      network_interfaces: "{{ network_card_name }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
